# Generated by Django 5.2.12 on 2026-03-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajo',
            options={'ordering': ['-fecha_subida']},
        ),
        migrations.AddField(
            model_name='trabajo',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título opcional (ej: "Manga floral")', max_length=100),
        ),
    ]
