# Generated by Django 5.2.12 on 2026-03-22 19:44

import portafolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_alter_trabajo_options_trabajo_fecha_subida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Texto alternativo SEO de la imagen. Se genera automáticamente si se deja vacío.', max_length=200, verbose_name='Alt text (SEO)'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='imagen',
            field=models.ImageField(upload_to=portafolio.models._seo_upload_path),
        ),
    ]
