# Generated by Django 5.2.12 on 2026-03-19 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='portafolio/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estilo', models.CharField(max_length=50)),
                ('tatuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_portafolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
