# Generated by Django 5.2.12 on 2026-03-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, help_text='Presentación que verán los clientes en tu perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Ej: Realismo, Blackwork, Neo-tradicional', max_length=120),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram',
            field=models.CharField(blank=True, help_text='Solo el @usuario, sin URL', max_length=60),
        ),
    ]
