# Generated by Django 5.2.12 on 2026-03-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_bio_perfil_especialidad_perfil_foto_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Estudio de Tatuajes', max_length=120)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='Número completo con código de país, sin espacios ni +', max_length=20)),
                ('instagram', models.CharField(blank=True, help_text='Solo el @usuario', max_length=60)),
                ('facebook', models.CharField(blank=True, help_text='URL completa o solo el usuario', max_length=120)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve para la página de inicio')),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('porcentaje_anticipo', models.PositiveSmallIntegerField(default=30, help_text='% de anticipo requerido para confirmar cita')),
            ],
            options={
                'verbose_name': 'Configuración del Estudio',
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='es_colaboracion',
            field=models.BooleanField(default=False, help_text='Marcar si es un artista invitado / colaboración temporal'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_fin_colab',
            field=models.DateField(blank=True, help_text='Fin de la colaboración (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_inicio_colab',
            field=models.DateField(blank=True, help_text='Inicio de la colaboración (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('propietario', 'Propietario'), ('tatuador', 'Tatuador'), ('cliente', 'Cliente')], default='cliente', max_length=15),
        ),
    ]
