# Generated by Django 5.2.12 on 2026-03-21 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_panel_propietario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionestudio',
            name='imagen_hero',
            field=models.ImageField(blank=True, help_text='Foto de fondo de la landing page (recomendado 1920x1080 px)', null=True, upload_to='hero/'),
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='anuncios/')),
                ('tipo', models.CharField(choices=[('colaboracion', 'Colaboración de artista'), ('concurso', 'Concurso de tatuajes'), ('voluntarios', 'Buscando voluntarios'), ('evento', 'Evento'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('fecha_evento', models.DateField(blank=True, help_text='Fecha del evento o inicio de la colaboración (se muestra en la tarjeta)', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Menor número aparece primero')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tatuador_asociado', models.ForeignKey(blank=True, help_text='Artista colaborador — se mostrará su portafolio en el anuncio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios_asociados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['orden', '-created_at'],
            },
        ),
    ]
