# Generated by Django 5.2.12 on 2026-03-21 04:38

import usuarios.skins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_landing_anuncios'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionestudio',
            name='idioma',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', help_text='Los visitantes podrán cambiarlo desde la página.', max_length=8, verbose_name='Idioma base'),
        ),
        migrations.AddField(
            model_name='configuracionestudio',
            name='skin',
            field=models.CharField(choices=usuarios.skins.skin_choices, default='noir', help_text='Paleta de colores y tipografía del sitio', max_length=20, verbose_name='Tema visual'),
        ),
    ]
