# Generated by Django 5.2.12 on 2026-03-22 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_imagenhero'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='estudio',
            field=models.ForeignKey(blank=True, help_text='Estudio al que pertenece este anuncio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='usuarios.configuracionestudio'),
        ),
        migrations.AddField(
            model_name='configuracionestudio',
            name='subdominio',
            field=models.SlugField(blank=True, help_text='Subdominio exclusivo del estudio. Ej: "studio33" → studio33.tudominio.com', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estudio',
            field=models.ForeignKey(blank=True, help_text='Estudio al que pertenece este usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='usuarios.configuracionestudio'),
        ),
        migrations.AlterField(
            model_name='configuracionestudio',
            name='plantilla_layout',
            field=models.CharField(choices=[('clasico', 'Clásico'), ('revista', 'Revista'), ('minimal', 'Minimal'), ('impacto', 'Impacto'), ('mosaico', 'Mosaico')], default='clasico', help_text='Disposición de las páginas públicas (landing, artístas, perfiles)', max_length=20, verbose_name='Plantilla de diseño'),
        ),
    ]
