# Generated by Django 5.2.12 on 2026-03-24 18:06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0010_logo_navbar_logo_hero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionestudio",
            name="logo_hero",
            field=models.ImageField(
                blank=True,
                help_text="Se muestra en el hero de la landing en lugar de la tipografía. Puede ser distinto al del navbar.",
                null=True,
                upload_to="logos/",
                verbose_name="Logo del hero",
            ),
        ),
    ]
