# Generated by Django 5.2.12 on 2026-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cancelada_por',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('tatuador', 'Tatuador')], max_length=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='notas_cancelacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('cotizada', 'Cotizada — Esperando anticipo'), ('anticipo_subido', 'Anticipo subido — Verificar depósito'), ('confirmada', 'Cita confirmada'), ('cancelada', 'Cancelada'), ('abierta', 'Fecha abierta — Por agendar')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_solicitada',
            field=models.DateField(),
        ),
    ]
