# Generated by Django 5.2.12 on 2026-03-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_cancelada_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_solicitada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
