# Generated by Django 5.2.12 on 2026-03-20 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_alter_cotizacion_fecha_solicitada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(choices=[('tatuador', 'Tatuador'), ('cliente', 'Cliente')], max_length=10)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='cotizaciones.cotizacion')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
