# Generated by Django 5.2.12 on 2026-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='notas_cliente',
            field=models.TextField(blank=True, help_text='Descripción libre: ideas, referencias, detalles especiales, etc.'),
        ),
    ]
