# Generated by Django 5.2.12 on 2026-03-19 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion')),
                ('tatuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_tatuador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
