# Generated by Django 5.2.12 on 2026-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=15),
        ),
        migrations.AddField(
            model_name='cita',
            name='recordatorio_dia_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='recordatorio_semana_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
