# Generated by Django 5.2.12 on 2026-03-21 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_estado_cita_recordatorio_dia_enviado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('evento', 'Evento / Convención'), ('viaje_nacional', 'Viaje a otro estado'), ('viaje_internacional', 'Viaje internacional'), ('otro', 'Otro')], default='otro', max_length=25)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional para el cliente')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad donde trabajará (solo para viajes)', max_length=100)),
                ('pais', models.CharField(blank=True, default='México', help_text='País (solo para viajes)', max_length=80)),
                ('publico', models.BooleanField(default=True, help_text='Si está activo, los clientes pueden ver este periodo en tu perfil público')),
                ('tatuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_agenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
