# Generated by Django 5.2.12 on 2026-03-19 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('token_acceso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estilo', models.CharField(max_length=50)),
                ('zona_cuerpo', models.CharField(max_length=100)),
                ('tamano', models.CharField(max_length=50)),
                ('imagen_referencia', models.ImageField(upload_to='referencias/')),
                ('fecha_solicitada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aceptada', 'Aceptada - Esperando anticipo'), ('pagada', 'Anticipo Recibido - Lista para agendar')], default='pendiente', max_length=20)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_anticipo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprobante_anticipo', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tatuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
